name: Build and publish component

on:
  workflow_call:
    inputs:
      ComponentName:
        required: true
        type: string
      Registry:
        required: true
        type: string
      Tag:
        required: true
        type: string
      ImageName:
        required: true
        type: string
      SecondaryTag:
        required: false
        type: string
        default: "latest"
    secrets:
      RegistryUsername:
        required: true
      RegistryPassword:
        required: true

jobs:
  build-and-push-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.Registry }}
          username: ${{ secrets.RegistryUsername }}
          password: ${{ secrets.RegistryPassword }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.Registry }}/${{ inputs.ImageName }}-${{ inputs.ComponentName }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ inputs.ComponentName }}
          push: true
          tags: |
            ${{ inputs.Registry }}/${{ inputs.ImageName }}-${{ inputs.ComponentName }}:${{ inputs.Tag }}
            ${{ inputs.Registry }}/${{ inputs.ImageName }}-${{ inputs.ComponentName }}:${{ inputs.SecondaryTag }}
          labels: ${{ steps.meta.outputs.labels }}
